### ISSUE TITLE
Can't connect to the network server

### ISSUE THREAD

**Issue by Kandars** [Radfordhound/GMod-Dupe-Downloader#1]
I tried downloading a dupe today
https://steamcommunity.com/sharedfiles/filedetails/?id=266987829
(that being it)
and it gave me with this error
http://i.imgur.com/BEUklG9.png

so basically it refuses anything

**Comment by sonic4380** [comment]
same here :(

**Comment by Radfordhound** [comment]
Hi, thanks for noticing this bug! Looking into it right now. Hopefully should be fixed soon.

**Comment by Radfordhound** [comment]
So basically the problem was that I coded the dupe downloader to get dupe information using the ever-so-wonderful [http://steamworkshopdownloader.com](http://steamworkshopdownloader.com/). Only problem was, the site went down mysteriously and as such the tool stopped working.

Luckily for us, however, the site appears to have magically just come back up. As a result of this, the tool is working correctly once again and all is well (at least for now). :)

Thanks to everyone for being patient with this! Sorry for the trouble. I'll try to find some other method of downloading dupes and integrate that into the mod loader in the future in-case the site goes down again. But for now, at least, it should be working.
